# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='书名')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('price', models.IntegerField(verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.IntegerField(choices=[(1, '人文社科'), (2, '经济管理'), (3, '励志与成功'), (4, '科技'), (5, '文学艺术'), (6, '少儿')], verbose_name='科类')),
                ('subtypes', models.CharField(max_length=32, verbose_name='子类')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.Category', verbose_name='分类'),
        ),
    ]
