# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格'),
        ),
    ]
