# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0003_books_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='country',
            field=models.CharField(max_length=32, verbose_name='国家'),
        ),
    ]
