# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='角色')),
            ],
            options={
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='类型')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoadmin.Roles', verbose_name='角色')),
            ],
            options={
                'verbose_name_plural': '用户类型表',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='ut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoadmin.UserType', verbose_name='用户类型'),
        ),
    ]
